config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :apparats do
    member do
      patch :update_description
      patch :add_contact
      patch :remove_contact
    end
  end
  patch "/goto", to: "apparats#goto"
  
  resources :users do
    resources :apparats_permits, only: [:create, :update, :destroy]
    resources :companies_permits, only: [:create, :update, :destroy]
  end
  
  resources :companies do
    resources :contacts, except: [:index] 
  end
  
  root to: "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :registerable :recoverable

  devise :database_authenticatable, :rememberable, :trackable, :validatable

  validates :name, presence: true  

  has_many :companies_permits, dependent: :destroy
  has_many :companies, through: :companies_permits

  has_many :apparats_permits, dependent: :destroy
  has_many :apparats, through: :apparats_permits

  def not_permited_apparats
    Apparat.all - self.apparats
  end

  def not_permited_companies
    Company.all - self.companies
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index
  
  def index
    @users = policy_scope User
  end

  def new
    @user = User.new
    authorize @user
  end

  def edit
    authorize @user
  end

  def create
    @user = User.new(secure_params)
    authorize @user
    if @user.save
      redirect_to @user, success: "Нового користувача створено."
    else
      render :new
    end
  end

  def show
    authorize @user
    @permited_apparats = @user.apparats_permits
    @permited_companies = @user.companies_permits
  end

  def update
    authorize @user
    if @user.update(secure_params)
      redirect_to @user, success: "Інформацію користувача оновлено."
    else
      render :edit
    end
  end

  def destroy
    authorize @user
    @user.destroy
    redirect_to users_path, success: "Користувача видалено."
  end

  private

  def secure_params
    params.require(:user).permit(:name, :email, :admin, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_apparats_table.html.erb
<% if @user.apparats.any? %>
  <h2 class="text-center">Призначені пристрої</h2>
  <table class="table">
    <thead>
      <tr>
        <th><strong>Назва</strong></th>
        <th><strong>ID</strong></th>
        <th><strong>Роль</strong></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @permited_apparats.each do |apparat| %>
        <tr>
          <td><strong><%= link_to apparat.apparat.name, apparat.apparat %></strong></td>
          <td><strong><%= apparat.apparat.id %></strong></td>
          <td>
            <%= form_for([apparat.user, apparat]) do |f| %>
              <%= f.select :role, ApparatsPermit.roles.keys %>
              <%= f.check_box :locked %>
              <%= f.submit "Змінити", data: {confirm: "Дійсно змінити роль?"}, class: "btn btn-xs btn-warning" %>
            <% end %>
          </td>
          <td><%= link_to "Видалити", [apparat.user, apparat], method: :delete, data: {confirm: "Впевнений що хочеш видалити роль?"}, class: "btn btn-xs btn-danger"%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% elsif%>
  <h2>Нема призначених пристроїв</h2>
<% end %>
<% if @user.not_permited_apparats.any? %>
  <%= render "apparats_permits/new" %>
<% end %>

app/views/users/_companies_table.html.erb
<% if @user.companies.any? %>
  <h2 class="text-center">Призначені компанії</h2>
  <table class="table">
    <thead>
      <tr>
        <th><strong>Назва</strong></th>
        <th><strong>Роль</strong></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @permited_companies.each do |permit| %>
        <tr>
          <td><strong><%= link_to permit.company.name, permit.company %>:</strong></td>
          <td>
            <%= form_for [permit.user, permit] do |f| %>
              <%= f.select :role, CompaniesPermit.roles.keys %>
              <%= f.submit "Змінити", data: {confirm: "Дійсно змінити роль?"}, class: "btn btn-xs btn-warning" %>
            <% end %>
          </td>
          <td>
            <%= link_to "Видалити", [permit.user, permit], method: :delete, data: {confirm: "Впевнений що хочеш видалити роль?"}, class: "btn btn-xs btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% elsif %>
  <h2>Нема призначених компаній</h2>
<% end %>

<% if @user.not_permited_companies.any? %>
  <%= render "companies_permits/new" %>
<% end %>

app/views/users/_form.html.erb
<div class="container"> 
  <div class="grey-back text-center session-form">
    <%= form_for @user do |f| %>
      <%= render "shared/error_messages", object: @user %>
      <div class="form-group text-left">
        <%= f.label :name, "Ім'я" %>
        <%= f.text_field :name, autofocus: true, class: "form-control" %>
      </div>
      <div class="form-group text-left">
        <%= f.label :email, "Пошта" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="form-group text-left">
        <%= f.label :password, "Пароль" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="ckeckbox text-left">
        <%= f.check_box :admin %>
        <%= f.label :admin, "Адміністратор" %>
      </div>
      <div>
        <%= f.submit yield(:button_text), class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div class="list-item">
  <% if current_user.admin? %>
    <%= link_to user_path(user) do %>
      <div class="row list-item-header">
        <span class="col-md-3 col-sm-3"><%= user.name %></span>
        <span class="col-md-3 col-sm-3"><%= user.email %></span>
        <span class="col-md-3 col-sm-3"><%= user.current_sign_in_ip %></span>
        <span class="col-md-3 col-sm-3">
          <% if user.admin? %>
            <strong>Administrator</strong>
          <% end %>
        </span>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:button_text, "Редагувати") %>
<h1 class="text-center">Редагування інформації про інженера</h1>
<%= render "form" %>

app/views/users/index.html.erb
<div class="container text-center">
  <% if current_user.admin? %>
    <%= link_to "Новий Інженер", new_user_path, class: "btn btn-default new-record" %>
  <% end %>

  <%= render @users %>
</div>

app/views/users/new.html.erb
<% provide(:button_text, "Створити") %>
<h1 class="text-center">Створення нового інженера</h1>
<%= render "form" %>

app/views/users/show.html.erb
<div class="container">
  
  <h1 style="text-align: center;">Інформація про інженера</h1>

  <table class="table">
    <tbody>
      <tr>
        <td><strong>Ім'я:</strong> <%= @user.name %></td>
        <td><strong>Пошта:</strong> <%= @user.email %></td>
        <td><strong>Останній IP з якого зайшов в систему:</strong> <%= @user.current_sign_in_ip %></td>
        <% if @user.admin? %>
           <td><strong>Адміністратор:</strong> <%= @user.admin %></td>
        <% end %>
      </tr>
    </tbody> 
  </table>

  <% if current_user.admin? %>
    <%= link_to "Редагувати інформацію", edit_user_path(@user), class: "btn btn-warning btn-xs" %>
  <% end %>
  <% if current_user.admin? and @user != current_user %>
    <%= link_to "Видалити інженера", user_path(@user), data: {confirm: "Впевнений що хочеш видалити інженера?"}, method: :delete, class: "btn btn-danger btn-xs" %>
  <% end %>

    <div class="row">
      <div class="col-xs-6">
        <%= render "users/apparats_table" %>
      </div>
      <div class="col-xs-6">
        <%= render "users/companies_table" %>
      </div>
    </div>
</div>