config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :apparats do
    member do
      patch :update_description
      patch :add_contact
      patch :remove_contact
    end
  end
  patch "/goto", to: "apparats#goto"
  
  resources :users do
    resources :apparats_permits, only: [:create, :update, :destroy]
    resources :companies_permits, only: [:create, :update, :destroy]
  end
  
  resources :companies do
    resources :contacts, except: [:index] 
  end
  
  root to: "home#index"
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence: true
  has_many :apparats
  has_many :companies_permits, dependent: :destroy
  has_many :users, through: :companies_permits
  has_many :contacts, dependent: :destroy
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  def index
    @companies = policy_scope Company
  end

  def new
    @company = Company.new
    authorize @company
  end

  def edit
    authorize @company
  end

  def show
    authorize @company
  end

  def create
    @company = Company.new(company_params)
    authorize @company
    if @company.save
      redirect_to right_redirect
      flash[:success] = "Company was successfully created."
    else
      render :new
    end
  end

  def update
    authorize @company
    if @company.update(company_params)
      redirect_to right_redirect

      flash[:success] = "Company was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    authorize @company
    @company.destroy
    redirect_to companies_path
    flash[:success] = "Company was successfully deleted."
  end

  private

    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(policy(Company).permitted_attributes)
    end

    # Determine redirect path depend on user policy.
    def right_redirect
      if policy(@company).update?
        edit_apparat_path(@company)
      else
        @company
      end
    end
end

app/views/companies/_company.html.erb
<div class="list-item">
  <% if policy(company).update? %>
    <%= link_to edit_company_path(company) do %>
      <div class="row list-item-header">
        <span class="col-md-6 col-sm-6 text-center">
          <%= company.name %>
        </span>
      </div>
      <p>
        <%= company.description %>
      </p>
    <% end %>
  <% else %>
    <%= link_to company_path(company) do %>
      <div class="row list-item-header">
        <span class="col-md-6 col-sm-6 text-center">
          <%= company.name %>
        </span>
      </div>
      <p>
        <%= company.description %>
      </p>
    <% end %>
  <% end %>

</div>

app/views/companies/_contacts.html.erb
<h2>Контакти: </h2>
<div class="row">
  <% @company.contacts.each do |contact| %>
    <div>
      <div class="col-md-5 col-sm-5 crop-text">
        <% if policy(contact).update? %>
          <%= link_to contact.name, edit_company_contact_url(@company, contact) %>
        <% else %>
          <%= link_to contact.name, company_contact_url(@company, contact) %>
        <% end %>
      </div>
    
      <div class="col-md-5 col-sm-5">
        <%= contact.phone %>
        <% if contact.default %>
           (основний)
         <% end %>
      </div>
      
      <div class="col-md-2 col-sm-2">
        <% if policy(contact).destroy? %>
          <%= link_to "x", company_contact_path(@company, contact),
              method: :delete,
              data: { confirm: "Видалити контакт?" },
              class: "btn btn-danger btn-xs" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<%= link_to "Новий контакт", new_company_contact_url(@company), class: "btn btn-xs btn-primary" %></li>

app/views/companies/_form.html.erb
<div class="main-page">
  <%= form_for @company do |f| %>
    <div class="information">
      <div class="container">
        <%= render "shared/error_messages", object: @company %>
        
        <div class="row">
          <div class="col-md-4 col-sm-4">
            <h2><%= f.label :name, "Назва" %></h2>
            <%= f.text_field :name, class: "whitebox"%>
          </div>

          <div class="col-md-4 col-sm-4">
            <h2><%= f.label :phone, "Телефон" %></h2>
            <%= f.text_field :phone, class: "whitebox" %>
          </div>
        </div>

        <% if @company.id %>
        <div class="row">
          <div class="col-md-6 col-sm-6">
            <%= render "contacts" %>
          </div>
          <div class="col-md-6 col-sm-6">
            <%= render "users" %>
          </div>
        </div>
        <% end %>

        <div>
          <h2><%= f.label :description, "Опис" %></h2>
          <%= f.text_area :description, rows: "10", class: "whitebox" %>
        </div>
      </div>
    </div>

    <div class="container">
      <% if @company.id && policy(@company).destroy? %> 
        <%= link_to "Видалити", @company, method: :delete, data: { confirm: "Впевнений що хочеш видати компанію?" }, class: "btn btn-danger pull-right" %>
      <% end %>
      <%= f.submit yield(:button_text), class: "btn btn-default pull-right" %>
    </div>
  <% end %>
</div>

app/views/companies/_users.html.erb
<% if current_user.admin? %>
  <h2>Інженери:</h2>
  <ul>
    <% @company.users.each do |user| %>
      <li>
        <%= link_to user.name, user %> 
        <%= user.companies_permits.find_by(company: @company).role %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/companies/edit.html.erb
<% provide(:button_text, "Редагувати") %>
<%= render "form" %>

app/views/companies/index.html.erb
<div class="container text-center">
  <% if current_user.admin? %>
    <%= link_to "Нова Компанія", new_company_path, class: "btn btn-default new-record" %>
  <% end %>

  <%= render @companies %>
</div>

app/views/companies/new.html.erb
<% provide(:button_text, "Створити") %>
<%= render "form" %>

app/views/companies/show.html.erb
<div class="main-page">
  <div class="information">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-sm-4-">
          <h2>Назва:</h2>
          <div class="whitebox"><%= @company.name %></div>
        </div>
        <div class="col-md-4 col-sm-4-">
          <h2>Телефон:</h2>
          <div class="whitebox"><%= @company.phone %></div>
        </div>
      </div>
      <div><%= render "contacts" %></div>
      <h2>Опис:</h2>
      <div class="whitebox"><%= simple_format(@company.description) %></div>
    </div>
  </div>
</div>