config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :apparats do
    member do
      patch :update_description
      patch :add_contact
      patch :remove_contact
    end
  end
  patch "/goto", to: "apparats#goto"
  
  resources :users do
    resources :apparats_permits, only: [:create, :update, :destroy]
    resources :companies_permits, only: [:create, :update, :destroy]
  end
  
  resources :companies do
    resources :contacts, except: [:index] 
  end
  
  root to: "home#index"
end

app/models/apparat.rb
class Apparat < ApplicationRecord
  validates :name, presence: true
  enum product_type: [:phones, :computer_laptop, :server, :thin_client, :router, :switch, 
                      :printer_scanner_mfp, :internet_settings, :other_information]
  belongs_to :company, optional: true
  has_many :apparats_permits, dependent: :destroy
  has_many :users, through: :apparats_permits
  has_and_belongs_to_many :contacts

  scope :product_type, -> (product_type) { where product_type: product_type }
  scope :company, -> (company_id) { where company_id: company_id }
  scope :desc_fragment, -> (desc_fragment) { where "description like ?", "%#{desc_fragment}%" }

  def not_added_contacts
    if self.company.present?
      self.company.contacts - self.contacts
    else
      []
    end
  end

  def users_without_permit
    User.all - self.users
  end
end

app/controllers/apparats_controller.rb
class ApparatsController < ApplicationController
  
  before_action :set_apparat, only: [:show, :edit, :update, :destroy, 
                                     :update_description, :add_contact,
                                     :remove_contact]
  after_action :verify_authorized, except: [:index, :update_description]
  after_action :verify_policy_scoped, only: [:index ]
  
  def index
    @apparats = policy_scope(Apparat)
    @apparats = @apparats.company(params[:company_id]) if params[:company_id].present?
    @apparats = @apparats.product_type(params[:product_type]) if params[:product_type].present?
    @apparats = @apparats.desc_fragment(params[:desc_fragment]) if params[:desc_fragment].present?
    @apparats_size = @apparats.size

    respond_to do |format|
      format.html { @apparats }
      format.js
    end
  end

  def new
    @apparat = Apparat.new
    authorize @apparat
  end

  def edit
    @users = User.all
    @permits = @apparat.apparats_permits
    authorize @apparat
  end

  def show
    @users = User.all
    @permits = @apparat.apparats_permits
    authorize @apparat
  end

  def create
    @apparat = Apparat.new(apparat_params)
    @company = Company.find(params[:company_id]) if params[:company_id].present?
    authorize @apparat
    if @apparat.save
      create_permit @apparat
      redirect_to right_redirect
      flash[:success] = "Новий пристрій створено."
    else
      render :new
    end
  end

  def update
    authorize @apparat
    if @apparat.update(apparat_params)
      redirect_to right_redirect
      flash[:success] = "Інформацію про пристрій оновлено."
    else
      render :edit
    end
  end

  # def destroy
  #   authorize @apparat
  #   @apparat.destroy
  #   redirect_to apparats_path
  #   flash[:success] = "Item was successfully deleted."
  # end

  def update_description
    date = DateTime.now.strftime("%Y-%m-%d %H:%m")
    desc = "#{@apparat.description}\n\r#{date} (#{current_user.name}): #{params[:description]}"
    @apparat.update(description: desc)
    flash[:success] = "Добавлено нову інформацію в опис."
    redirect_to right_redirect
  end

  def add_contact
    authorize @apparat
    @contact = Contact.find(params[:contact_id])
    @apparat.contacts << @contact
    respond_to do |format|
      format.html { redirect_to right_redirect }
      format.js
      format.json { render json: @apparat.errors, status: :unprocessable_entity }
    end
  end
  
  def remove_contact
    authorize @apparat
    contact = Contact.find(params[:contact_id])
    @apparat.contacts.delete(contact)
    respond_to do |format|
      format.html { redirect_to right_redirect @apparat }
      format.js
      format.json { render json: @apparat.errors, status: :unprocessable_entity }
    end
  end

  def goto
    if Apparat.where(id: params[:id]).exists?
      set_apparat
      authorize @apparat
      redirect_to right_redirect
    else
      authorize Apparat
      flash[:danger] = "В базі нема пристрою з номером #{params[:id]}."
      redirect_to root_path
    end
  end

  private

    def set_apparat
      @apparat = Apparat.find(params[:id])
    end

    def apparat_params
      params.require(:apparat).permit(policy(Apparat).permitted_attributes)
    end

    # Create permit for new apparat. If current_user has permits on assigned
    # company he will get the same role in this apparat. If user admin - 
    # don't create any permits.
    def create_permit(apparat)
      unless current_user.admin?
      company = Company.find(apparat_params[:company_id]) if apparat_params[:company_id].present?
        if company and current_user.companies_permits.find_by(company: company)
          role = current_user.companies_permits.find_by(company: company).role
        else
          role = "newbie"
        end
        apparat.apparats_permits.create(user: current_user, role: role)
      end
    end

    # Determine redirect path depend on user policy.
    def right_redirect
      if policy(@apparat).update?
        edit_apparat_path(@apparat)
      else
        @apparat
      end
    end
end

app/helpers/apparats_helper.rb
module ApparatsHelper
  def short_name(name)
    name.length > 25 ?
      "#{name[0..25]}..." :
      name
  end
end

app/views/apparats/_apparat.html.erb
<div class="list-item">
  <% if policy(apparat).update? %>
    <%# <%= link_to (edit_apparat_path(apparat)) do %1> %>
      <div>
        <div class="row list-item-header">
          <span class="col-md-1 text-center"><%= apparat.id %></span>
          <span class="col-md-3 crop-text"><%= apparat.name %></span>
          <span class="col-md-2 ip-address"><%= apparat.ip_address if apparat.ip_address %></span>
          <span class="col-md-6 crop-text"><%= apparat.company.name if apparat.company %></span>
        </div>
    <%= link_to (edit_apparat_path(apparat)) do %>
        <p><%= apparat.description %></p>
      </div>
    <% end %>
  <% else %>
    <%# <%= link_to (apparat_path(apparat)) do %1> %>
      <div>
        <div class="row list-item-header">
          <span class="col-md-1 text-center"><%= apparat.id %></span>
          <span class="col-md-3 crop-text"><%= apparat.name %></span>
          <span class="col-md-2 ip-address"><%= apparat.ip_address if apparat.ip_address %></span>
          <span class="col-md-6 crop-text"><%= apparat.company.name if apparat.company %></span>
        </div>
    <%= link_to (apparat_path(apparat)) do %>
        <p><%= apparat.description %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/apparats/_append_user_form.html.erb
<% if policy(ApparatsPermit).create? %>
  <div class="col-md-6 col-sm-6">
    <%= select_tag :user, options_for_select(@apparat.users_without_permit.map {|user| [user.name, user.id]}) %>
  </div>
  <div class="col-md-1 col-sm-1">
    <%= check_box_tag :locked, {}, class: "user-role-locked" %>
  </div>
  <div class="col-md-4 col-sm-4">
    <%= select_tag :role, options_for_select(ApparatsPermit.roles.keys) %>
  </div>
  <div class="col-md-1 col-sm-1">
    <%= link_to "+", "#", class: "new-apparat-permit-btn btn btn-xs btn-success" %>
  </div>
<% end %>

app/views/apparats/_contact_selection.html.erb
<% if policy(@apparat).add_contact? and !@apparat.not_added_contacts.empty? %>
    <%= select_tag :contact_id,
      options_for_select(@apparat.not_added_contacts.map{|c| [c.name, c.id]}),
      class: "append-contact-selection"
      %>
    <%= link_to "+", "#", class: "append-contact-btn btn btn-xs btn-success" %>
<% end %>

app/views/apparats/_contacts_list.html.erb
<h2>Контакти:</h2>
<div class="contact-buttons">
  <%= link_to "Перегляд", "#", class: "btn btn-default", id: "show-contacts-list" %>
  <span id="notice" class="ajax-alert"></span>
</div>
<div id="contacts-list" class="row">
  <div class="list-items">
    <%= render @apparat.contacts %>
  </div>
  <div class="col-md-12 col-sm-12 text-left">
    <div class="append-contact-form">
      <%= render "contact_selection" %>
    </div>
  </div>
</div>

app/views/apparats/_form.html.erb
<div class="main-page">
  <%= form_for @apparat do |f| %>
    <div class="information">
      <div class="container">
        <%= render "shared/error_messages", object: @apparat %>
        <h1 class="text-left apparat-id" data-apparat-id="<%= @apparat.id %>">Пристрій № <%= @apparat.id %></h1>
        
        <div class="row">
          <div class="col-md-2 col-sm-2">
            <h2><%= f.label :name, "Назва" %></h2>
            <%= f.text_field :name, class: "whitebox" %>
          </div>
          <div class="col-md-2 col-sm-2">
            <h2><%= f.label :type, "Тип" %></h2>
            <%= f.select(:product_type, 
                         Apparat.product_types.keys.map {|type| [type.titleize,type]}, 
                         {include_blank: true}, { class: "whitebox"}) %>
          </div>
          <div class="col-md-2 col-sm-2">
            <h2><%= f.label :company, "Компанія" %></h2>
            <%= f.collection_select :company_id, Company.all, :id, :name, 
                                    {include_blank: true}, class: "whitebox" %>
          </div>
          <div class="col-md-6 col-sm-6">
            <% if current_user.admin? && !@apparat.new_record? %>
              <%= render "users" %>
            <% end %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-2 col-sm-2">
            <h2><%= f.label :serial_number, "Серійний №" %></h2>
            <%= f.text_field :serial_number, class: "whitebox" %>
          </div>
          <div class="col-md-2 col-sm-2">
            <h2><%= f.label :ip_address, "ІР адреса" %></h2>
            <%= f.text_field :ip_address, class: "whitebox" %>
          </div>
          <div class="col-md-8 col-sm-8">
            <% if !@apparat.new_record? %>
              <%= render "contacts_list" %>
            <% end %>
          </div>
        </div>
        <div>
          <h2><%= f.label :description, "Опис" %></h2>
          <%= f.text_area :description, rows: "10", class: "whitebox" %>
        </div>
      </div>
    </div>

    <div class="container">
      <%= f.submit yield(:button_text), class: "btn btn-default pull-right" %>
    </div>
  <% end %>
</div>

app/views/apparats/_update_description_form.html.erb
<div class="form">
  <%= form_tag update_description_apparat_path(@apparat), method: :patch do %>
    <div class="form_group">
      <%= text_area_tag :description, nil, class: "form-control" %><br>
      <%= submit_tag "Добавити опис", class: "btn btn-default pull-right" %>
    </div>
  <% end %>
</div>

app/views/apparats/_users.html.erb
<h2>Закріплені інженери</h2>
<div class="user-buttons">
  <%= link_to "Перегляд", "#", class: "show-users-list btn btn-default" %>
  <span id="notice" class="ajax-alert"></span>
</div>
<div class="users-list row">
  <div class="apparat-permits-users-list">
  <%= render @permits %>
  </div>

  <div class="append-user-form">
    <%= render "append_user_form" %>
  </div>
</div>

app/views/apparats/add_contact.js.erb
$(".list-items").append("<%= j(render @contact) %>");

$(".contact-buttons span#notice")
  .html("Контакт додано.")
  .fadeIn()
  .delay(1000)
  .fadeOut();

app/views/apparats/edit.html.erb
<% provide(:button_text, "Оновити") %>
<%= render "form" %>

app/views/apparats/index.html.erb
<div class="container">
  <%= render "shared/filter" %>
  <%= render @apparats %>
</div>

app/views/apparats/index.js.erb
$('#results').empty();
$('#results').append('<%= j(render @apparats) %>').hide().slideDown("fast");
$(".results-size").html("<%= @apparats_size %>")

app/views/apparats/new.html.erb
<% provide(:button_text, "Створити") %>
<%= render "form" %>

app/views/apparats/remove_contact.js.erb
$(".remove-contact-from-list").bind("ajax:success", function() {
    itemId = $(this).data("id");
    $("#contacts-list-item-"+itemId).remove();
    $(".append-contact-form").html("<%= j(render "contact_selection") %>");
});

$(".contact-buttons span#notice")
  .html("Контакт відкріплено.")
  .fadeIn()
  .delay(1000)
  .fadeOut();

app/views/apparats/show.html.erb
<div class="main-page">
  <div class="information">
    <div class="container">
      <h1 class="text-left apparat-id" data-apparat-id="<%= @apparat.id %>">Пристрій № <%= @apparat.id %></h1>
      <div class="row">
        <div class="col-md-2 col-sm-2">
          <h2>Назва</h2>
          <span class="whitebox">
            <%= @apparat.name %>
          </span>
        </div>
        <div class="col-md-2 col-sm-2">
          <h2>Тип</h2>
          <span class="whitebox">
            <%= @apparat.product_type.humanize if @apparat.product_type %>
          </span>
        </div>
        <div class="col-md-2 col-sm-2">
          <h2>Компанія</h2>
          <span class="whitebox">
            <%= @apparat.company.name if @apparat.company %>
          </span>
        </div>
        <div class="col-md-6 col-sm-6">
          <% if current_user.admin? %>
            <%= render "users" %>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 col-sm-2">
          <h2>Серійний №</h2>
          <span class="whitebox">
            <%= @apparat.serial_number if @apparat.serial_number %>
          </span>
        </div>
        <div class="col-md-2 col-sm-2">
          <h2>ІР адреса</h2>
          <span class="whitebox">
            <%= @apparat.ip_address %>
          </span>
        </div>
        <div class="col-md-8 col-sm-8">
          <%= render "contacts_list" %>
        </div>
      </div>

      <h2>Опис</h2>
      <span class="whitebox description">
        <%= simple_format(@apparat.description) %>
      </span>
    </div>
  </div>
  <div class="container">
    <div class="apparat-add-description">
      <% if policy(@apparat).update_description? %>
        <%= render "apparats/update_description_form" %>
      <% end %>
    </div>
  </div>
</div>