config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :apparats do
    member do
      patch :update_description
      patch :add_contact
      patch :remove_contact
    end
  end
  patch "/goto", to: "apparats#goto"
  
  resources :users do
    resources :apparats_permits, only: [:create, :update, :destroy]
    resources :companies_permits, only: [:create, :update, :destroy]
  end
  
  resources :companies do
    resources :contacts, except: [:index] 
  end
  
  root to: "home#index"
end

app/views/layouts/_navigation.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">PLANTAGO</a>
      </div>
    <div id="navbar" class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li><%= render "shared/goto" %></li>
      <% if current_user %>
        <% if current_user.admin? %>
          <li><%= link_to "Інженери", users_path %></li>
        <% end %>
        <li>
          <% if policy(Apparat).create? %>
            <%= link_to "Новий Пристрій", new_apparat_path %>
          <% end %>
        </li>
        <li><%= link_to "Компанії", companies_path %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li id="current-user-name"><strong><%= current_user.name.humanize %></strong></li>
        <li><%= link_to "Вийти", destroy_user_session_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "Зайти", new_user_session_path %></li>
      <% end %>
    </ul>  
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_notifications.html.erb
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %> <%= message_type %>-dismissable">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
      <div class="text-center"> <%= message %> </div>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plantago</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= render "layouts/navigation" %>
    <%= render "layouts/notifications" %>
    <%= yield %>
  </body>
</html>